# Generated by Django 4.1.7 on 2023-03-15 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_mail_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='send_to',
            new_name='receiver',
        ),
    ]
